import { Product, Category, BlogPost } from '../types'

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Cleansers', slug: 'cleansers', description: 'Gentle yet effective formulas', image: '/images/Card.png', productCount: 12 },
  { id: '2', name: 'Serums', slug: 'serums', description: 'Targeted treatment solutions', image: '/images/Card-2.png', productCount: 18 },
  { id: '3', name: 'Moisturizers', slug: 'moisturizers', description: 'Deep hydration & nourishment', image: '/images/Card-3.png', productCount: 15 },
  { id: '4', name: 'Sunscreen', slug: 'sunscreen', description: 'Broad spectrum protection', image: '/images/Card 2.png', productCount: 8 },
  { id: '5', name: 'Eye Care', slug: 'eye-care', description: 'Delicate eye area treatments', image: '/images/Card 4.png', productCount: 10 },
  { id: '6', name: 'Masks', slug: 'masks', description: 'Intensive weekly rituals', image: '/images/Card 5.png', productCount: 9 },
]

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Radiance Brightening Serum',
    slug: 'radiance-brightening-serum',
    tagline: 'Luminous skin in 14 days',
    description: 'A potent blend of Vitamin C, niacinamide, and hyaluronic acid that visibly reduces dark spots and evens skin tone.',
    longDescription: 'Our Radiance Brightening Serum combines the power of 15% stable Vitamin C with 5% niacinamide and a trio of hyaluronic acids. This science-backed formula works synergistically to brighten, hydrate, and protect your skin from environmental stressors. Clinically tested and dermatologist-approved.',
    price: 68,
    comparePrice: 85,
    images: [
      '/images/Card-2.png',
      '/images/Card 6.png',
      '/images/Content.png',
    ],
    category: CATEGORIES[1],
    categoryId: '2',
    tags: ['brightening', 'vitamin c', 'anti-aging'],
    ingredients: ['Ascorbic Acid 15%', 'Niacinamide 5%', 'Hyaluronic Acid', 'Ferulic Acid', 'Vitamin E'],
    benefits: ['Brightens dark spots', 'Evens skin tone', 'Hydrates deeply', 'Boosts collagen', 'Antioxidant protection'],
    howToUse: 'Apply 3–4 drops to cleansed skin morning and evening. Follow with moisturizer and SPF in the morning.',
    volume: '30ml / 1 fl oz',
    rating: 4.8,
    reviewCount: 342,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Gentle Foam Cleanser',
    slug: 'gentle-foam-cleanser',
    tagline: 'Pure, soft, perfectly balanced',
    description: 'A pH-balanced foaming cleanser with ceramides and green tea extract that cleanses without stripping.',
    price: 38,
    images: [
      '/images/Card.png',
      '/images/Content (1).png',
    ],
    category: CATEGORIES[0],
    categoryId: '1',
    tags: ['cleanser', 'gentle', 'all skin types'],
    rating: 4.7,
    reviewCount: 218,
    isNew: true,
    isFeatured: true,
    inStock: true,
    createdAt: '2024-02-01',
  },
  {
    id: '3',
    name: 'Silk Barrier Moisturizer',
    slug: 'silk-barrier-moisturizer',
    tagline: 'Restore. Protect. Glow.',
    description: 'A rich yet lightweight moisturizer formulated with ceramides, squalane, and peptides to strengthen the skin barrier.',
    price: 72,
    comparePrice: 90,
    images: [
      '/images/Card-3.png',
      '/images/Content (2).png',
    ],
    category: CATEGORIES[2],
    categoryId: '3',
    tags: ['moisturizer', 'barrier', 'ceramides'],
    rating: 4.9,
    reviewCount: 486,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    createdAt: '2024-01-01',
  },
  {
    id: '4',
    name: 'Solar Shield SPF 50+',
    slug: 'solar-shield-spf-50',
    tagline: 'Invisible protection, all day comfort',
    description: 'A lightweight, non-greasy SPF 50+ sunscreen with blue light protection and antioxidant complex.',
    price: 45,
    images: [
      '/images/Card 2.png',
      '/images/Content (3).png',
    ],
    category: CATEGORIES[3],
    categoryId: '4',
    tags: ['sunscreen', 'spf50', 'daily'],
    rating: 4.6,
    reviewCount: 193,
    isNew: true,
    inStock: true,
    createdAt: '2024-02-15',
  },
  {
    id: '5',
    name: 'Retinol Renewal Night Cream',
    slug: 'retinol-renewal-night-cream',
    tagline: 'Wake up to younger-looking skin',
    description: 'Encapsulated retinol with bakuchiol and peptides for visible wrinkle reduction without irritation.',
    price: 95,
    images: [
      '/images/Card 4.png',
      '/images/Content (4).png',
    ],
    category: CATEGORIES[2],
    categoryId: '3',
    tags: ['retinol', 'anti-aging', 'night'],
    rating: 4.8,
    reviewCount: 267,
    isBestseller: true,
    inStock: true,
    createdAt: '2024-01-20',
  },
  {
    id: '6',
    name: 'Luminous Eye Concentrate',
    slug: 'luminous-eye-concentrate',
    tagline: 'Brighter eyes, instantly',
    description: 'A multi-action eye cream with caffeine, peptides and vitamin K to target dark circles and puffiness.',
    price: 58,
    images: [
      '/images/Card 5.png',
      '/images/Content (5).png',
    ],
    category: CATEGORIES[4],
    categoryId: '5',
    tags: ['eye cream', 'dark circles', 'peptides'],
    rating: 4.7,
    reviewCount: 154,
    isNew: true,
    inStock: true,
    createdAt: '2024-03-01',
  },
  {
    id: '7',
    name: 'Kaolin Clay Detox Mask',
    slug: 'kaolin-clay-detox-mask',
    tagline: 'Deep cleanse in 15 minutes',
    description: 'A purifying kaolin and bentonite clay mask with activated charcoal and tea tree to draw out impurities.',
    price: 42,
    images: [
      '/images/Card 6.png',
      '/images/Content 2.png',
    ],
    category: CATEGORIES[5],
    categoryId: '6',
    tags: ['mask', 'clay', 'detox', 'pores'],
    rating: 4.5,
    reviewCount: 128,
    inStock: true,
    createdAt: '2024-01-10',
  },
  {
    id: '8',
    name: 'Hyaluronic Acid Booster',
    slug: 'hyaluronic-acid-booster',
    tagline: '72-hour plumping hydration',
    description: 'A triple-weight hyaluronic acid serum that delivers intense moisture at every layer of the skin.',
    price: 55,
    comparePrice: 68,
    images: [
      '/images/Card-1.png',
      '/images/Content 3.png',
    ],
    category: CATEGORIES[1],
    categoryId: '2',
    tags: ['hyaluronic', 'hydration', 'plumping'],
    rating: 4.9,
    reviewCount: 521,
    isBestseller: true,
    inStock: true,
    createdAt: '2023-11-01',
  },
]

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'The Science Behind Vitamin C Serums',
    slug: 'science-behind-vitamin-c-serums',
    excerpt: 'Discover why Vitamin C is the gold standard in brightening skincare and how to maximize its effectiveness.',
    body: '',
    coverImage: '/images/Content.png',
    category: 'Ingredient Deep Dive',
    author: 'Dr. Sophie Martin',
    readTime: 6,
    publishedAt: '2024-02-20',
  },
  {
    id: '2',
    title: 'Building Your Perfect Morning Routine',
    slug: 'building-perfect-morning-routine',
    excerpt: 'From cleanser to SPF, we break down the exact order for maximum efficacy of your morning skincare.',
    body: '',
    coverImage: '/images/Content (1).png',
    category: 'Routines',
    author: 'Emma Caldwell',
    readTime: 5,
    publishedAt: '2024-02-14',
  },
  {
    id: '3',
    title: 'Retinol 101: Everything You Need to Know',
    slug: 'retinol-101-everything-need-to-know',
    excerpt: 'The most powerful anti-aging ingredient, demystified. We answer your most pressing retinol questions.',
    body: '',
    coverImage: '/images/Content (2).png',
    category: 'Ingredient Deep Dive',
    author: 'Dr. Sophie Martin',
    readTime: 8,
    publishedAt: '2024-01-28',
  },
]

export const TESTIMONIALS = [
  {
    id: '1',
    name: 'Sarah M.',
    handle: '@sarahglows',
    avatar: '/images/cc1.png',
    product: 'Radiance Brightening Serum',
    rating: 5,
    text: 'I\'ve tried countless serums over the years, but this one genuinely transformed my skin in just three weeks. My dark spots have visibly faded and my complexion is so much more even.',
  },
  {
    id: '2',
    name: 'Emma R.',
    handle: '@emmarskin',
    avatar: '/images/cc2.png',
    product: 'Silk Barrier Moisturizer',
    rating: 5,
    text: 'As someone with sensitive skin, finding products that don\'t cause breakouts is a constant struggle. The Silk Barrier Moisturizer is genuinely perfect — light, non-greasy, and my skin feels incredible.',
  },
  {
    id: '3',
    name: 'Olivia K.',
    handle: '@okbeauty',
    avatar: '/images/cc3.png',
    product: 'Hyaluronic Acid Booster',
    rating: 5,
    text: 'The plumping effect is real. I use this every morning under my moisturizer and my skin looks so much more hydrated and youthful. My friends keep asking what I\'m doing differently.',
  },
  {
    id: '4',
    name: 'Priya D.',
    handle: '@priyabeauty',
    avatar: '/images/cc1.png',
    product: 'Retinol Renewal Night Cream',
    rating: 5,
    text: 'Finally a retinol product that doesn\'t irritate my skin! I\'ve been using it for 2 months and the fine lines around my eyes have noticeably softened. Worth every penny.',
  },
]

export const NAV_LINKS = [
  { label: 'Our Products', href: '/shop' },
  { label: 'Journal', href: '/journal' },
  { label: 'About Us', href: '/about' },
  { label: 'Checkout', href: '/checkout' },
]

export const MARQUEE_ITEMS = [
  'Clean Beauty',
  'Dermatologist Tested',
  'Cruelty Free',
  'Vegan Formulas',
  'Sustainable Packaging',
  'Science-Backed',
  'No Parabens',
  'No Sulfates',
]
